language: swift
osx_image: xcode10.1
os: osx

install:
   - ./install_swiftlint.sh

script:
   - swiftlint
   - set -o pipefail && xcodebuild -project Do-It.xcodeproj -scheme Do-ItCoreTests -destination 'name=iPhone X' test | xcpretty
